# Generated by Django 2.2.7 on 2019-11-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAdmin',
        ),
        migrations.DeleteModel(
            name='PersonAdmin',
        ),
        migrations.DeleteModel(
            name='ProfilAdmin',
        ),
        migrations.DeleteModel(
            name='TicketAdmin',
        ),
    ]
