# Generated by Django 2.2.7 on 2019-11-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='customer',
            new_name='customers',
        ),
    ]
