# Generated by Django 2.2.7 on 2019-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0003_auto_20191109_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tickets',
            field=models.ManyToManyField(to='hotline.Ticket'),
        ),
    ]
