# Generated by Django 2.2.7 on 2019-11-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_person_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tickets',
        ),
    ]
