# Generated by Django 2.2.7 on 2019-12-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_ticket_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
