# Generated by Django 2.2.7 on 2019-11-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_auto_20191110_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='hotline.Person'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='hotline.Person'),
        ),
    ]
