# Generated by Django 2.2.7 on 2019-11-10 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0010_auto_20191110_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.RegexValidator(message="Postal code must be entered in the format: '99999'.", regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
