# Generated by Django 2.2.7 on 2019-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0011_auto_20191110_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='New customer', max_length=255, unique=True),
        ),
    ]
